name: Go Integration Tests

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read


jobs:
  go-test:
    name: Go Repository Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: src/go.mod
          cache-dependency-path: src/go.sum

      - name: Run tests
        working-directory: src
        run: go test -race -timeout 120s ./api-gateway/... ./scheduler/... ./executor/...
